//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AllTech.FrameWork
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sysfactLocalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sysfactLocalEntities object using the connection string found in the 'sysfactLocalEntities' section of the application configuration file.
        /// </summary>
        public sysfactLocalEntities() : base("name=sysfactLocalEntities", "sysfactLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sysfactLocalEntities object.
        /// </summary>
        public sysfactLocalEntities(string connectionString) : base(connectionString, "sysfactLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sysfactLocalEntities object.
        /// </summary>
        public sysfactLocalEntities(EntityConnection connection) : base(connection, "sysfactLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_facture> t_facture
        {
            get
            {
                if ((_t_facture == null))
                {
                    _t_facture = base.CreateObjectSet<t_facture>("t_facture");
                }
                return _t_facture;
            }
        }
        private ObjectSet<t_facture> _t_facture;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_facture EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_facture(t_facture t_facture)
        {
            base.AddObject("t_facture", t_facture);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sysfactLocalModel", Name="t_facture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_facture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_facture object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cree_Par">Initial value of the Cree_Par property.</param>
        /// <param name="numero_Facture">Initial value of the Numero_Facture property.</param>
        /// <param name="date_Creation">Initial value of the Date_Creation property.</param>
        public static t_facture Createt_facture(global::System.Int64 id, global::System.Int32 cree_Par, global::System.String numero_Facture, global::System.DateTime date_Creation)
        {
            t_facture t_facture = new t_facture();
            t_facture.ID = id;
            t_facture.Cree_Par = cree_Par;
            t_facture.Numero_Facture = numero_Facture;
            t_facture.Date_Creation = date_Creation;
            return t_facture;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Modifie_Par
        {
            get
            {
                return _Modifie_Par;
            }
            set
            {
                OnModifie_ParChanging(value);
                ReportPropertyChanging("Modifie_Par");
                _Modifie_Par = StructuralObject.SetValidValue(value, "Modifie_Par");
                ReportPropertyChanged("Modifie_Par");
                OnModifie_ParChanged();
            }
        }
        private Nullable<global::System.Int32> _Modifie_Par;
        partial void OnModifie_ParChanging(Nullable<global::System.Int32> value);
        partial void OnModifie_ParChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cree_Par
        {
            get
            {
                return _Cree_Par;
            }
            set
            {
                OnCree_ParChanging(value);
                ReportPropertyChanging("Cree_Par");
                _Cree_Par = StructuralObject.SetValidValue(value, "Cree_Par");
                ReportPropertyChanged("Cree_Par");
                OnCree_ParChanged();
            }
        }
        private global::System.Int32 _Cree_Par;
        partial void OnCree_ParChanging(global::System.Int32 value);
        partial void OnCree_ParChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numero_Facture
        {
            get
            {
                return _Numero_Facture;
            }
            set
            {
                OnNumero_FactureChanging(value);
                ReportPropertyChanging("Numero_Facture");
                _Numero_Facture = StructuralObject.SetValidValue(value, false, "Numero_Facture");
                ReportPropertyChanged("Numero_Facture");
                OnNumero_FactureChanged();
            }
        }
        private global::System.String _Numero_Facture;
        partial void OnNumero_FactureChanging(global::System.String value);
        partial void OnNumero_FactureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_Creation
        {
            get
            {
                return _Date_Creation;
            }
            set
            {
                OnDate_CreationChanging(value);
                ReportPropertyChanging("Date_Creation");
                _Date_Creation = StructuralObject.SetValidValue(value, "Date_Creation");
                ReportPropertyChanged("Date_Creation");
                OnDate_CreationChanged();
            }
        }
        private global::System.DateTime _Date_Creation;
        partial void OnDate_CreationChanging(global::System.DateTime value);
        partial void OnDate_CreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Modification
        {
            get
            {
                return _Date_Modification;
            }
            set
            {
                OnDate_ModificationChanging(value);
                ReportPropertyChanging("Date_Modification");
                _Date_Modification = StructuralObject.SetValidValue(value, "Date_Modification");
                ReportPropertyChanged("Date_Modification");
                OnDate_ModificationChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Modification;
        partial void OnDate_ModificationChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_ModificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Objet
        {
            get
            {
                return _ID_Objet;
            }
            set
            {
                OnID_ObjetChanging(value);
                ReportPropertyChanging("ID_Objet");
                _ID_Objet = StructuralObject.SetValidValue(value, "ID_Objet");
                ReportPropertyChanged("ID_Objet");
                OnID_ObjetChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Objet;
        partial void OnID_ObjetChanging(Nullable<global::System.Int32> value);
        partial void OnID_ObjetChanged();

        #endregion

    }

    #endregion

}
