//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTech_Facturation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiColumnComboEditorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MultiColumnComboEditorStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllTech_Facturation.Resources.MultiColumnComboEditorStrings", typeof(MultiColumnComboEditorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Drop Down Resizing.
        /// </summary>
        public static string AllowDropDownResizing {
            get {
                return ResourceManager.GetString("AllowDropDownResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Multiple Selection.
        /// </summary>
        public static string AllowMultipleSelection {
            get {
                return ResourceManager.GetString("AllowMultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box Visibility.
        /// </summary>
        public static string CheckBoxVisibility {
            get {
                return ResourceManager.GetString("CheckBoxVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filter.
        /// </summary>
        public static string CustomFilter {
            get {
                return ResourceManager.GetString("CustomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title field EndsWith .....
        /// </summary>
        public static string CustomFilterToolTip {
            get {
                return ResourceManager.GetString("CustomFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Value Action:.
        /// </summary>
        public static string CustomValueEnteredAction {
            get {
                return ResourceManager.GetString("CustomValueEnteredAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Mode:.
        /// </summary>
        public static string FilterMode {
            get {
                return ResourceManager.GetString("FilterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a footer template..
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Grid_CustomerId {
            get {
                return ResourceManager.GetString("Grid_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Grid_ShipCity {
            get {
                return ResourceManager.GetString("Grid_ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        public static string Grid_ShipName {
            get {
                return ResourceManager.GetString("Grid_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Drop Opened.
        /// </summary>
        public static string IsDropOpened {
            get {
                return ResourceManager.GetString("IsDropOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSelect Value Delimiter:.
        /// </summary>
        public static string MultiSelectValueDelimiter {
            get {
                return ResourceManager.GetString("MultiSelectValueDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Button Visibility.
        /// </summary>
        public static string ResetButtonVisibility {
            get {
                return ResourceManager.GetString("ResetButtonVisibility", resourceCulture);
            }
        }
    }
}
