//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multilingue.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multilingue.Resources.Langues", typeof(Langues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete invoice.
        /// </summary>
        public static string ctxFacture_menuItem_Delete {
            get {
                return ResourceManager.GetString("ctxFacture_menuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Invoice.
        /// </summary>
        public static string ctxFacture_menuItem_Edit {
            get {
                return ResourceManager.GetString("ctxFacture_menuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string ctxFacture_menuItem_New {
            get {
                return ResourceManager.GetString("ctxFacture_menuItem_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print invoice.
        /// </summary>
        public static string ctxFacture_menuItem_print {
            get {
                return ResourceManager.GetString("ctxFacture_menuItem_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enought Right for this operation.
        /// </summary>
        public static string Droit_privilege_Msg {
            get {
                return ResourceManager.GetString("Droit_privilege_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create  in this Date date this invoice, Inform your manager.
        /// </summary>
        public static string facture_Msg_Jourlimite {
            get {
                return ResourceManager.GetString("facture_Msg_Jourlimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by :.
        /// </summary>
        public static string factureAuditCrePar {
            get {
                return ResourceManager.GetString("factureAuditCrePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        public static string factureAuditDatecreation {
            get {
                return ResourceManager.GetString("factureAuditDatecreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last update:.
        /// </summary>
        public static string factureAuditDateModif {
            get {
                return ResourceManager.GetString("factureAuditDateModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation date:.
        /// </summary>
        public static string factureAuditDateValide {
            get {
                return ResourceManager.GetString("factureAuditDateValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update by:.
        /// </summary>
        public static string factureAuditModifpar {
            get {
                return ResourceManager.GetString("factureAuditModifpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit date.
        /// </summary>
        public static string factureAuditSortie {
            get {
                return ResourceManager.GetString("factureAuditSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark-Up.
        /// </summary>
        public static string factureEntete_marge {
            get {
                return ResourceManager.GetString("factureEntete_marge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkUp :.
        /// </summary>
        public static string factureEntete_marge2 {
            get {
                return ResourceManager.GetString("factureEntete_marge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional :.
        /// </summary>
        public static string factureEntete_prorata {
            get {
                return ResourceManager.GetString("factureEntete_prorata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax and Margin.
        /// </summary>
        public static string factureEntete_TaxeMArge {
            get {
                return ResourceManager.GetString("factureEntete_TaxeMArge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat :.
        /// </summary>
        public static string factureEntete_Tva {
            get {
                return ResourceManager.GetString("factureEntete_Tva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string factureEntete_Tva_Msg {
            get {
                return ResourceManager.GetString("factureEntete_Tva_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        public static string factureEnteteClient {
            get {
                return ResourceManager.GetString("factureEnteteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number :.
        /// </summary>
        public static string factureEnteteCommande {
            get {
                return ResourceManager.GetString("factureEnteteCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange :.
        /// </summary>
        public static string factureEnteteConverse {
            get {
                return ResourceManager.GetString("factureEnteteConverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        public static string factureEnteteDateCreate {
            get {
                return ResourceManager.GetString("factureEnteteDateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string factureEnteteDateDepot {
            get {
                return ResourceManager.GetString("factureEnteteDateDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department :.
        /// </summary>
        public static string factureEnteteDept {
            get {
                return ResourceManager.GetString("factureEnteteDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice currency:.
        /// </summary>
        public static string factureEnteteDeviseFact {
            get {
                return ResourceManager.GetString("factureEnteteDeviseFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expoitation:.
        /// </summary>
        public static string factureEnteteexploit {
            get {
                return ResourceManager.GetString("factureEnteteexploit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice # :.
        /// </summary>
        public static string factureEnteteFactyreNum {
            get {
                return ResourceManager.GetString("factureEnteteFactyreNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End day prestation:.
        /// </summary>
        public static string factureEnteteJourFin {
            get {
                return ResourceManager.GetString("factureEnteteJourFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestation Month:.
        /// </summary>
        public static string factureEnteteMoisP {
            get {
                return ResourceManager.GetString("factureEnteteMoisP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un avalaible:.
        /// </summary>
        public static string factureEnteteNonValide {
            get {
                return ResourceManager.GetString("factureEnteteNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object:.
        /// </summary>
        public static string factureEnteteObjet {
            get {
                return ResourceManager.GetString("factureEnteteObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Object:.
        /// </summary>
        public static string factureEnteteObjetNew {
            get {
                return ResourceManager.GetString("factureEnteteObjetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit date  :.
        /// </summary>
        public static string factureEnteteSortie {
            get {
                return ResourceManager.GetString("factureEnteteSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type customer.
        /// </summary>
        public static string factureEnteteStatutClient {
            get {
                return ResourceManager.GetString("factureEnteteStatutClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice status:.
        /// </summary>
        public static string factureEnteteStatutFacture {
            get {
                return ResourceManager.GetString("factureEnteteStatutFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension :.
        /// </summary>
        public static string factureEnteteSuspension {
            get {
                return ResourceManager.GetString("factureEnteteSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxe and Marge.
        /// </summary>
        public static string factureEnteteTaxeTitre {
            get {
                return ResourceManager.GetString("factureEnteteTaxeTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        public static string factureEnteteTotalFacture {
            get {
                return ResourceManager.GetString("factureEnteteTotalFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular invoice.
        /// </summary>
        public static string factureEntetetyperadio1 {
            get {
                return ResourceManager.GetString("factureEntetetyperadio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit invoice.
        /// </summary>
        public static string factureEntetetyperadio2 {
            get {
                return ResourceManager.GetString("factureEntetetyperadio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice type.
        /// </summary>
        public static string factureEntetetypeTitre {
            get {
                return ResourceManager.GetString("factureEntetetypeTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string factureGridDesc {
            get {
                return ResourceManager.GetString("factureGridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount HT.
        /// </summary>
        public static string factureGridMontantht {
            get {
                return ResourceManager.GetString("factureGridMontantht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string factureGridPrixunit {
            get {
                return ResourceManager.GetString("factureGridPrixunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string factureGridProd {
            get {
                return ResourceManager.GetString("factureGridProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string factureGridQuantite {
            get {
                return ResourceManager.GetString("factureGridQuantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Taxe.
        /// </summary>
        public static string factureGridtaxe {
            get {
                return ResourceManager.GetString("factureGridtaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Header invoice.
        /// </summary>
        public static string factureInfoEnteteTitre {
            get {
                return ResourceManager.GetString("factureInfoEnteteTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete line items.
        /// </summary>
        public static string factureLigneDelete {
            get {
                return ResourceManager.GetString("factureLigneDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another description.
        /// </summary>
        public static string factureLigneDesc {
            get {
                return ResourceManager.GetString("factureLigneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line items.
        /// </summary>
        public static string factureLigneLignes {
            get {
                return ResourceManager.GetString("factureLigneLignes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string factureLignePrixUnit {
            get {
                return ResourceManager.GetString("factureLignePrixUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string factureLigneProduit {
            get {
                return ResourceManager.GetString("factureLigneProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string factureLigneqte {
            get {
                return ResourceManager.GetString("factureLigneqte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Items.
        /// </summary>
        public static string factureLigneTitre {
            get {
                return ResourceManager.GetString("factureLigneTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line item.
        /// </summary>
        public static string factureLigneTooltibtnAdd {
            get {
                return ResourceManager.GetString("factureLigneTooltibtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string factureTabItemAudit {
            get {
                return ResourceManager.GetString("factureTabItemAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string factureTabItemTitre {
            get {
                return ResourceManager.GetString("factureTabItemTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel invoice.
        /// </summary>
        public static string factureTopbarTooltipCancel {
            get {
                return ResourceManager.GetString("factureTopbarTooltipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string factureTopbarTooltipClose {
            get {
                return ResourceManager.GetString("factureTopbarTooltipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New invoice.
        /// </summary>
        public static string factureTopbarTooltipNew {
            get {
                return ResourceManager.GetString("factureTopbarTooltipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string factureTopbarTooltipPrint {
            get {
                return ResourceManager.GetString("factureTopbarTooltipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string factureTopbarTooltipSave {
            get {
                return ResourceManager.GetString("factureTopbarTooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete invoice.
        /// </summary>
        public static string factureTopbarTooltipSupprime {
            get {
                return ResourceManager.GetString("factureTopbarTooltipSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull operation !.
        /// </summary>
        public static string factureVM_msgNewfacture {
            get {
                return ResourceManager.GetString("factureVM_msgNewfacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error&lt;10006&gt; Creation invoice failed.
        /// </summary>
        public static string factureVM_msgNewfacture_error {
            get {
                return ResourceManager.GetString("factureVM_msgNewfacture_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items invoice are require.
        /// </summary>
        public static string factureVM_NewFacture_ErrorrequireItemsMsg {
            get {
                return ResourceManager.GetString("factureVM_NewFacture_ErrorrequireItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date prestion is require filed.
        /// </summary>
        public static string factureVM_NewFacture_requireDateMsg {
            get {
                return ResourceManager.GetString("factureVM_NewFacture_requireDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise is require field.
        /// </summary>
        public static string factureVM_NewFacture_requireDeviseMsg {
            get {
                return ResourceManager.GetString("factureVM_NewFacture_requireDeviseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxe is require field.
        /// </summary>
        public static string factureVM_NewFacture_requireTaxeMsg {
            get {
                return ResourceManager.GetString("factureVM_NewFacture_requireTaxeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE CREATING MESSAGE.
        /// </summary>
        public static string factureVM_titreNewfacture {
            get {
                return ResourceManager.GetString("factureVM_titreNewfacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE ERROR Msg.
        /// </summary>
        public static string factureVM_titreNewfacture_error {
            get {
                return ResourceManager.GetString("factureVM_titreNewfacture_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error   !  Unable  Invoice Failed &lt;&lt;10006&gt;&gt;.
        /// </summary>
        public static string factureVM_UpdatefactureErrorMsg {
            get {
                return ResourceManager.GetString("factureVM_UpdatefactureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Validate .
        /// </summary>
        public static string factureVM_UpdatefactureInformation {
            get {
                return ResourceManager.GetString("factureVM_UpdatefactureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION UPDATE INVOICE.
        /// </summary>
        public static string factureVM_Updatefacturetitre {
            get {
                return ResourceManager.GetString("factureVM_Updatefacturetitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error  ! Validation Invoice Failed  .
        /// </summary>
        public static string factureVM_ValidatefactureErrormsg {
            get {
                return ResourceManager.GetString("factureVM_ValidatefactureErrormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Form.
        /// </summary>
        public static string fiche_Client {
            get {
                return ResourceManager.GetString("fiche_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Form.
        /// </summary>
        public static string fiche_Produit {
            get {
                return ResourceManager.GetString("fiche_Produit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Form.
        /// </summary>
        public static string fiche_Utilisateur {
            get {
                return ResourceManager.GetString("fiche_Utilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ucheck All.
        /// </summary>
        public static string gridbtnDeselect {
            get {
                return ResourceManager.GetString("gridbtnDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string gridbtnselect {
            get {
                return ResourceManager.GetString("gridbtnselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string gridClient {
            get {
                return ResourceManager.GetString("gridClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date #.
        /// </summary>
        public static string gridDatecreation {
            get {
                return ResourceManager.GetString("gridDatecreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation date.
        /// </summary>
        public static string gridDatevalidation {
            get {
                return ResourceManager.GetString("gridDatevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Service.
        /// </summary>
        public static string gridMois {
            get {
                return ResourceManager.GetString("gridMois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Ops.
        /// </summary>
        public static string gridNomSiteOps {
            get {
                return ResourceManager.GetString("gridNomSiteOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice#.
        /// </summary>
        public static string gridNumfacture {
            get {
                return ResourceManager.GetString("gridNumfacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objet.
        /// </summary>
        public static string gridObjet {
            get {
                return ResourceManager.GetString("gridObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared by.
        /// </summary>
        public static string gridPrepareBy {
            get {
                return ResourceManager.GetString("gridPrepareBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string gridSataut {
            get {
                return ResourceManager.GetString("gridSataut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total TTC.
        /// </summary>
        public static string gridTotal {
            get {
                return ResourceManager.GetString("gridTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string hst_facture_research {
            get {
                return ResourceManager.GetString("hst_facture_research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating invoice.
        /// </summary>
        public static string hst_facture_validate_14001 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Validate.
        /// </summary>
        public static string hst_facture_validate_14003 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice out.
        /// </summary>
        public static string hst_facture_validate_14004 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Suspending.
        /// </summary>
        public static string hst_facture_validate_14005 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice unable.
        /// </summary>
        public static string hst_facture_validate_14006 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit invoice.
        /// </summary>
        public static string hst_facture_validate_14007 {
            get {
                return ResourceManager.GetString("hst_facture_validate_14007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string hst_header_action_a {
            get {
                return ResourceManager.GetString("hst_header_action_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string hst_header_action_b {
            get {
                return ResourceManager.GetString("hst_header_action_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validations invoice.
        /// </summary>
        public static string hst_header_action_c {
            get {
                return ResourceManager.GetString("hst_header_action_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Customers Not yent  Invoicing.
        /// </summary>
        public static string hst_OverviwTitle {
            get {
                return ResourceManager.GetString("hst_OverviwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current invoice.
        /// </summary>
        public static string hst_TabItemHeaderArchive_msg {
            get {
                return ResourceManager.GetString("hst_TabItemHeaderArchive_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernières factures traitées.
        /// </summary>
        public static string hst_TabItemHeaderOverview_msg {
            get {
                return ResourceManager.GetString("hst_TabItemHeaderOverview_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code  saling record is require.
        /// </summary>
        public static string journalVente_NotifCode_Msg {
            get {
                return ResourceManager.GetString("journalVente_NotifCode_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is require.
        /// </summary>
        public static string journalVente_NotifDateJournal_Msg {
            get {
                return ResourceManager.GetString("journalVente_NotifDateJournal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Invoice found.
        /// </summary>
        public static string journalVente_NotifJvgenerate_Msg {
            get {
                return ResourceManager.GetString("journalVente_NotifJvgenerate_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ther is already recod  Sale Exist.
        /// </summary>
        public static string journalVente_NotifJvgenerateExist_Msg {
            get {
                return ResourceManager.GetString("journalVente_NotifJvgenerateExist_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type your user name.
        /// </summary>
        public static string lblselecttextlogin {
            get {
                return ResourceManager.GetString("lblselecttextlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type tour password.
        /// </summary>
        public static string lblselecttextPassword {
            get {
                return ResourceManager.GetString("lblselecttextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices current.
        /// </summary>
        public static string lblUserAfficheCours {
            get {
                return ResourceManager.GetString("lblUserAfficheCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices created.
        /// </summary>
        public static string lblUserAfficheCreated {
            get {
                return ResourceManager.GetString("lblUserAfficheCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during loading summary page Contact your administrato.
        /// </summary>
        public static string lblUserAfficheError {
            get {
                return ResourceManager.GetString("lblUserAfficheError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR LOADING SUMMARY PAGE.
        /// </summary>
        public static string lblUserAfficheErrorTitre {
            get {
                return ResourceManager.GetString("lblUserAfficheErrorTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices outPut.
        /// </summary>
        public static string lblUserAfficheSorties {
            get {
                return ResourceManager.GetString("lblUserAfficheSorties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices suspended.
        /// </summary>
        public static string lblUserAfficheSuspendu {
            get {
                return ResourceManager.GetString("lblUserAfficheSuspendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices validated.
        /// </summary>
        public static string lblUserAfficheValidee {
            get {
                return ResourceManager.GetString("lblUserAfficheValidee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string logginVies_database {
            get {
                return ResourceManager.GetString("logginVies_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Closing.
        /// </summary>
        public static string messageCloseMsg {
            get {
                return ResourceManager.GetString("messageCloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSING MESSAGE FORM.
        /// </summary>
        public static string messageCloseTitre {
            get {
                return ResourceManager.GetString("messageCloseTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string mNuAdmin {
            get {
                return ResourceManager.GetString("mNuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp Invoice.
        /// </summary>
        public static string mNuAdmin_Admin {
            get {
                return ResourceManager.GetString("mNuAdmin_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datas refs.
        /// </summary>
        public static string mNuAdmin_Datarefs {
            get {
                return ResourceManager.GetString("mNuAdmin_Datarefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string mNuAdmin_Parametres {
            get {
                return ResourceManager.GetString("mNuAdmin_Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp Invoice.
        /// </summary>
        public static string mNuAdminAdmin_Datarefs {
            get {
                return ResourceManager.GetString("mNuAdminAdmin_Datarefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guid.
        /// </summary>
        public static string mNuAide {
            get {
                return ResourceManager.GetString("mNuAide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mNuApropos {
            get {
                return ResourceManager.GetString("mNuApropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mNuFile {
            get {
                return ResourceManager.GetString("mNuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string mNuFile_fermer {
            get {
                return ResourceManager.GetString("mNuFile_fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mNuFile_quitter {
            get {
                return ResourceManager.GetString("mNuFile_quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string mNuOperation {
            get {
                return ResourceManager.GetString("mNuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/Import.
        /// </summary>
        public static string mNuOperation_Extract {
            get {
                return ResourceManager.GetString("mNuOperation_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic invoice.
        /// </summary>
        public static string mNuOperation_Hst {
            get {
                return ResourceManager.GetString("mNuOperation_Hst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling book.
        /// </summary>
        public static string MNuOperation_Jv {
            get {
                return ResourceManager.GetString("MNuOperation_Jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output control.
        /// </summary>
        public static string mNuOperation_Sorties {
            get {
                return ResourceManager.GetString("mNuOperation_Sorties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Up Invoice Of.
        /// </summary>
        public static string MsgArchive_Display {
            get {
                return ResourceManager.GetString("MsgArchive_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You want to delete this Item ?.
        /// </summary>
        public static string msgSuppression {
            get {
                return ResourceManager.GetString("msgSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETING MESSAGE.
        /// </summary>
        public static string msgSuppressiontitre {
            get {
                return ResourceManager.GetString("msgSuppressiontitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval date searching.
        /// </summary>
        public static string RecherchebuttonToolTip {
            get {
                return ResourceManager.GetString("RecherchebuttonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string RechercheCmbClient {
            get {
                return ResourceManager.GetString("RechercheCmbClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user Loggin.
        /// </summary>
        public static string shellVm_MsgBadLoggincontent {
            get {
                return ResourceManager.GetString("shellVm_MsgBadLoggincontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGGIN ERROR.
        /// </summary>
        public static string shellVm_MsgBadLogginTitre {
            get {
                return ResourceManager.GetString("shellVm_MsgBadLogginTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string shellVm_MsgBadMotpcontent {
            get {
                return ResourceManager.GetString("shellVm_MsgBadMotpcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error.
        /// </summary>
        public static string shellVm_MsgBadMotpTitre {
            get {
                return ResourceManager.GetString("shellVm_MsgBadMotpTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account is locked, please contact administrator.
        /// </summary>
        public static string shellVm_MsgCompteLockcontent {
            get {
                return ResourceManager.GetString("shellVm_MsgCompteLockcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUMPT LOCKED.
        /// </summary>
        public static string shellVm_MsgCompteLockTitre {
            get {
                return ResourceManager.GetString("shellVm_MsgCompteLockTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte est expiré et sera verouilleé, veuillez contacter l&apos;administrateur.
        /// </summary>
        public static string shellVm_MsgcontentCompteStatus {
            get {
                return ResourceManager.GetString("shellVm_MsgcontentCompteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT PROBLEME.
        /// </summary>
        public static string shellVm_MsgTitreCompteStatus {
            get {
                return ResourceManager.GetString("shellVm_MsgTitreCompteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string splitBoutonFiltre {
            get {
                return ResourceManager.GetString("splitBoutonFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string splitBoutonFiltreByClient {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by customer .
        /// </summary>
        public static string splitBoutonFiltreByClient_tooltip {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByClient_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string splitBoutonFiltreByDate {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Date.
        /// </summary>
        public static string splitBoutonFiltreByDate_tooltip {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByDate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string splitBoutonFiltreByFacture {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Invoce number.
        /// </summary>
        public static string splitBoutonFiltreByFacture_tooltip {
            get {
                return ResourceManager.GetString("splitBoutonFiltreByFacture_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing/Exports.
        /// </summary>
        public static string splitBoutonImpressions {
            get {
                return ResourceManager.GetString("splitBoutonImpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string splitBoutonImpressionsExport {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All invoices.
        /// </summary>
        public static string splitBoutonImpressionsExport_List {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsExport_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLoad invoices selected.
        /// </summary>
        public static string splitBoutonImpressionsExport_select {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsExport_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to dowload in excel format invoices selected.
        /// </summary>
        public static string splitBoutonImpressionsExportTooltip {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string splitBoutonImpressionsprint {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print selected.
        /// </summary>
        public static string splitBoutonImpressionsprintList {
            get {
                return ResourceManager.GetString("splitBoutonImpressionsprintList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string splitBoutonOperation {
            get {
                return ResourceManager.GetString("splitBoutonOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this button allow to change status to  un validate status  of bill selected.
        /// </summary>
        public static string splitBoutonOperationTooltipNonValide {
            get {
                return ResourceManager.GetString("splitBoutonOperationTooltipNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this button allow to change status to out status of bill selected.
        /// </summary>
        public static string splitBoutonOperationTooltipSortie {
            get {
                return ResourceManager.GetString("splitBoutonOperationTooltipSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this button allow to change status to suspend status   of bill selected.
        /// </summary>
        public static string splitBoutonOperationTooltipSuspension {
            get {
                return ResourceManager.GetString("splitBoutonOperationTooltipSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this button allow to validate bill selected.
        /// </summary>
        public static string splitBoutonOperationTooltipValidation {
            get {
                return ResourceManager.GetString("splitBoutonOperationTooltipValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string splitBoutonRechercheDateDebut {
            get {
                return ResourceManager.GetString("splitBoutonRechercheDateDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string splitBoutonRechercheDateFin {
            get {
                return ResourceManager.GetString("splitBoutonRechercheDateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchs.
        /// </summary>
        public static string splitBoutonRecherches {
            get {
                return ResourceManager.GetString("splitBoutonRecherches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ssss {
            get {
                return ResourceManager.GetString("ssss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Up.
        /// </summary>
        public static string TabItemHeaderArchive {
            get {
                return ResourceManager.GetString("TabItemHeaderArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Historic.
        /// </summary>
        public static string titreFormulaire {
            get {
                return ResourceManager.GetString("titreFormulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English(En).
        /// </summary>
        public static string toolbarLangueEn {
            get {
                return ResourceManager.GetString("toolbarLangueEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain(Sp).
        /// </summary>
        public static string toolbarLangueEs {
            get {
                return ResourceManager.GetString("toolbarLangueEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French(Fr).
        /// </summary>
        public static string toolbarLangueFr {
            get {
                return ResourceManager.GetString("toolbarLangueFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese(Pt).
        /// </summary>
        public static string toolbarLanguePt {
            get {
                return ResourceManager.GetString("toolbarLanguePt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPORARY ACCOUNT:.
        /// </summary>
        public static string toolbarPopUpCpmtTemp {
            get {
                return ResourceManager.GetString("toolbarPopUpCpmtTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New licence.
        /// </summary>
        public static string toolbarPopUpLicense_tooltip {
            get {
                return ResourceManager.GetString("toolbarPopUpLicense_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome ton new installation:.
        /// </summary>
        public static string toolbarPopUpMsInstal {
            get {
                return ResourceManager.GetString("toolbarPopUpMsInstal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil:.
        /// </summary>
        public static string toolbarProfile {
            get {
                return ResourceManager.GetString("toolbarProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User connected :.
        /// </summary>
        public static string toolbarUserConnecter {
            get {
                return ResourceManager.GetString("toolbarUserConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites lists.
        /// </summary>
        public static string toolbaTitreListe {
            get {
                return ResourceManager.GetString("toolbaTitreListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close form.
        /// </summary>
        public static string toolbaToolTip_fermer {
            get {
                return ResourceManager.GetString("toolbaToolTip_fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh historic grid.
        /// </summary>
        public static string toolbaToolTip_refresh {
            get {
                return ResourceManager.GetString("toolbaToolTip_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string tooltipbtnAnnul {
            get {
                return ResourceManager.GetString("tooltipbtnAnnul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string tooltipDeconecter {
            get {
                return ResourceManager.GetString("tooltipDeconecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic invoice.
        /// </summary>
        public static string tooltipHst {
            get {
                return ResourceManager.GetString("tooltipHst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling book.
        /// </summary>
        public static string tooltipJvente {
            get {
                return ResourceManager.GetString("tooltipJvente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtNom {
            get {
                return ResourceManager.GetString("txtNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Monthly Invoice Summary.
        /// </summary>
        public static string userAfficheTitre {
            get {
                return ResourceManager.GetString("userAfficheTitre", resourceCulture);
            }
        }
    }
}
