//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTech.FrameWork.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CommonStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllTech.FrameWork.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ConfigurationPanel_Header_Options {
            get {
                return ResourceManager.GetString("ConfigurationPanel_Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme:.
        /// </summary>
        public static string ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Time.
        /// </summary>
        public static string XW_BindingTime {
            get {
                return ResourceManager.GetString("XW_BindingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Points.
        /// </summary>
        public static string XW_DataPoints {
            get {
                return ResourceManager.GetString("XW_DataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string XW_Date {
            get {
                return ResourceManager.GetString("XW_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string XW_Options {
            get {
                return ResourceManager.GetString("XW_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string XW_Settings {
            get {
                return ResourceManager.GetString("XW_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Theme.
        /// </summary>
        public static string XW_ThemeSupport_DefaultTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IG Theme.
        /// </summary>
        public static string XW_ThemeSupport_IGTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_IGTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010 Blue Theme.
        /// </summary>
        public static string XW_ThemeSupport_Office2010BlueTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Office2010BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string XW_ThemeSupport_Themes {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string XW_Time {
            get {
                return ResourceManager.GetString("XW_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span.
        /// </summary>
        public static string XW_TimeSpan {
            get {
                return ResourceManager.GetString("XW_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string XW_Value {
            get {
                return ResourceManager.GetString("XW_Value", resourceCulture);
            }
        }
    }
}
