//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTech.FrameWork.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PivotGridStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PivotGridStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllTech.FrameWork.Resources.PivotGridStrings", typeof(PivotGridStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmatically change the default aggregator for Amount of sale to:.
        /// </summary>
        public static string XPG_Aggregators_Label {
            get {
                return ResourceManager.GetString("XPG_Aggregators_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow CompactLayout.
        /// </summary>
        public static string XPG_Allow_CompactLayout {
            get {
                return ResourceManager.GetString("XPG_Allow_CompactLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate cell type!.
        /// </summary>
        public static string XPG_Cell_Type_Not_Located {
            get {
                return ResourceManager.GetString("XPG_Cell_Type_Not_Located", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cell.
        /// </summary>
        public static string XPG_CellSelection_CellOnly {
            get {
                return ResourceManager.GetString("XPG_CellSelection_CellOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select column.
        /// </summary>
        public static string XPG_CellSelection_ColumnOnly {
            get {
                return ResourceManager.GetString("XPG_CellSelection_ColumnOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select row and column.
        /// </summary>
        public static string XPG_CellSelection_RowAndColumn {
            get {
                return ResourceManager.GetString("XPG_CellSelection_RowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select row.
        /// </summary>
        public static string XPG_CellSelection_RowOnly {
            get {
                return ResourceManager.GetString("XPG_CellSelection_RowOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C2}.
        /// </summary>
        public static string XPG_Data_AmountOfSale_DisplayFormat {
            get {
                return ResourceManager.GetString("XPG_Data_AmountOfSale_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of sale.
        /// </summary>
        public static string XPG_Data_AmountOfSale_DisplayName {
            get {
                return ResourceManager.GetString("XPG_Data_AmountOfSale_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofia;London;New York;Berlin;Seattle;Mellvile;Tokyo.
        /// </summary>
        public static string XPG_Data_Cities {
            get {
                return ResourceManager.GetString("XPG_Data_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Data.
        /// </summary>
        public static string XPG_Data_CubeMetadata_DisplayName {
            get {
                return ResourceManager.GetString("XPG_Data_CubeMetadata_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file could not be downloaded..
        /// </summary>
        public static string XPG_Data_Error {
            get {
                return ResourceManager.GetString("XPG_Data_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All locations.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Location_All {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Location_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Location_Name {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Product_All {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Product_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Product_Name {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sellers.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Seller_All {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Seller_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller name.
        /// </summary>
        public static string XPG_Data_HierarchyDescriptors_Seller_Name {
            get {
                return ResourceManager.GetString("XPG_Data_HierarchyDescriptors_Seller_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units sold.
        /// </summary>
        public static string XPG_Data_NumberOfUnits_DisplayName {
            get {
                return ResourceManager.GetString("XPG_Data_NumberOfUnits_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories;Bikes;Clothing;Components.
        /// </summary>
        public static string XPG_Data_ProductCategories {
            get {
                return ResourceManager.GetString("XPG_Data_ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string XPG_Data_PropertyNames_City {
            get {
                return ResourceManager.GetString("XPG_Data_PropertyNames_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string XPG_Data_PropertyNames_Date {
            get {
                return ResourceManager.GetString("XPG_Data_PropertyNames_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string XPG_Data_PropertyNames_Product {
            get {
                return ResourceManager.GetString("XPG_Data_PropertyNames_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string XPG_Data_PropertyNames_Seller {
            get {
                return ResourceManager.GetString("XPG_Data_PropertyNames_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Smith;Alfredo Fetuchini;Howard Sprouse;Russell Shorter;Nicholas Carmona;Larry Lieb;Carl Costello;Benjamin Dupree;Bryan Culver;Monica Freitag;Lydia Burson;Harold Garvin;Walter Pang;David Haley;Glenn Landeros;Harry Tyler;Stanley Brooker;Antonio Charbonneau;Brandon Mckim;Claudia Kobayashi;Benjamin Meekins;Mark Slater;Kathe Pettel;Elisa Longbottom.
        /// </summary>
        public static string XPG_Data_SellerNames {
            get {
                return ResourceManager.GetString("XPG_Data_SellerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string XPG_Data_UnitPrice_DisplayName {
            get {
                return ResourceManager.GetString("XPG_Data_UnitPrice_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string XPG_DataSelectorNoGrid_Columns {
            get {
                return ResourceManager.GetString("XPG_DataSelectorNoGrid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string XPG_DataSelectorNoGrid_Rows {
            get {
                return ResourceManager.GetString("XPG_DataSelectorNoGrid_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string XPG_DGM_Metadata {
            get {
                return ResourceManager.GetString("XPG_DGM_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string XPG_DGM_Mixed {
            get {
                return ResourceManager.GetString("XPG_DGM_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string XPG_DGM_Property {
            get {
                return ResourceManager.GetString("XPG_DGM_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files|*.xls.
        /// </summary>
        public static string XPG_Excel_Export_ExcelFileFilter {
            get {
                return ResourceManager.GetString("XPG_Excel_Export_ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from PivotGrid.
        /// </summary>
        public static string XPG_Excel_Export_Sheet_Name {
            get {
                return ResourceManager.GetString("XPG_Excel_Export_Sheet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string XPG_Excel_Export_Total {
            get {
                return ResourceManager.GetString("XPG_Excel_Export_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet1 Data.
        /// </summary>
        public static string XPG_ExcelFileDataSource_CubeDisplayName {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_CubeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} units..
        /// </summary>
        public static string XPG_ExcelFileDataSource_DimSettings_DisplayFormat {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_DimSettings_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string XPG_ExcelFileDataSource_DimSettings_DisplayName {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_DimSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string XPG_ExcelFileDataSource_DimSettings_Units_SrcPropName {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_DimSettings_Units_SrcPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C3}.
        /// </summary>
        public static string XPG_ExcelFileDataSource_ExcelFormatDest {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_ExcelFormatDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;$\&quot;#,##0.00_);[Red]\\(\&quot;$\&quot;#,##0.00\\).
        /// </summary>
        public static string XPG_ExcelFileDataSource_ExcelFormatSrc {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_ExcelFormatSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_All {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_AllDates {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_AllDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllValues.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_AllValues {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_AllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_Members {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarters.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_Quarters {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string XPG_ExcelFileDataSource_HierarchyDesc_Years {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_HierarchyDesc_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Date].[Date].
        /// </summary>
        public static string XPG_ExcelFileDataSource_InitialColumns {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_InitialColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelData.
        /// </summary>
        public static string XPG_ExcelFileDataSource_InitialCube {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_InitialCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string XPG_ExcelFileDataSource_InitialMeasures {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_InitialMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Region].[Region].
        /// </summary>
        public static string XPG_ExcelFileDataSource_InitialRows {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_InitialRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet1.
        /// </summary>
        public static string XPG_ExcelFileDataSource_WorksheetName {
            get {
                return ResourceManager.GetString("XPG_ExcelFileDataSource_WorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Collapse_All {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Collapse_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Expand {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to Half-Years.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Expand_HalfYears {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Expand_HalfYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to Months.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Expand_Months {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Expand_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to Quarters.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Expand_Quarters {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Expand_Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to Years.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Expand_Years {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Expand_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Expansion Level:.
        /// </summary>
        public static string XPG_ExpandToLevelCB_Select_Expansion_Level {
            get {
                return ResourceManager.GetString("XPG_ExpandToLevelCB_Select_Expansion_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export column headers.
        /// </summary>
        public static string XPG_Export_Column_Headers {
            get {
                return ResourceManager.GetString("XPG_Export_Column_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Row Headers.
        /// </summary>
        public static string XPG_Export_Row_Headers {
            get {
                return ResourceManager.GetString("XPG_Export_Row_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string XPG_Export_To_Excel {
            get {
                return ResourceManager.GetString("XPG_Export_To_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string XPG_Filtering_Filter {
            get {
                return ResourceManager.GetString("XPG_Filtering_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string XPG_Filtering_Months {
            get {
                return ResourceManager.GetString("XPG_Filtering_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show data for the last.
        /// </summary>
        public static string XPG_Filtering_ShowDataForTheLast {
            get {
                return ResourceManager.GetString("XPG_Filtering_ShowDataForTheLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data generation complete!.
        /// </summary>
        public static string XPG_LargeDataHandling_DataGenComplete {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_DataGenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data generation will start when you click the OK button.
        /// </summary>
        public static string XPG_LargeDataHandling_DataGenWillStart {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_DataGenWillStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Data.
        /// </summary>
        public static string XPG_LargeDataHandling_GenerateData {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_GenerateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Data.
        /// </summary>
        public static string XPG_LargeDataHandling_GeneratingData {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_GeneratingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data to PivotGrid.
        /// </summary>
        public static string XPG_LargeDataHandling_LoadingData {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of records to generate:.
        /// </summary>
        public static string XPG_LargeDataHandling_SelectNumRecords {
            get {
                return ResourceManager.GetString("XPG_LargeDataHandling_SelectNumRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string XPG_Legend {
            get {
                return ResourceManager.GetString("XPG_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sales.
        /// </summary>
        public static string XPG_LiveUpdate_AllSales {
            get {
                return ResourceManager.GetString("XPG_LiveUpdate_AllSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest sales.
        /// </summary>
        public static string XPG_LiveUpdate_LatestSales {
            get {
                return ResourceManager.GetString("XPG_LiveUpdate_LatestSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1} has sold {2} items from {3} for {4} dollars.
        /// </summary>
        public static string XPG_LiveUpdate_UpdateString {
            get {
                return ResourceManager.GetString("XPG_LiveUpdate_UpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data from excel file.
        /// </summary>
        public static string XPG_Load_Data_From_Excel_File {
            get {
                return ResourceManager.GetString("XPG_Load_Data_From_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load selected state.
        /// </summary>
        public static string XPG_Load_Selected_State {
            get {
                return ResourceManager.GetString("XPG_Load_Selected_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot Chart.
        /// </summary>
        public static string XPG_Pivot_Chart {
            get {
                return ResourceManager.GetString("XPG_Pivot_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot Data.
        /// </summary>
        public static string XPG_Pivot_Data {
            get {
                return ResourceManager.GetString("XPG_Pivot_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot Grid Data.
        /// </summary>
        public static string XPG_Pivot_Grid_Data {
            get {
                return ResourceManager.GetString("XPG_Pivot_Grid_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current view.
        /// </summary>
        public static string XPG_Save_Current_View {
            get {
                return ResourceManager.GetString("XPG_Save_Current_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is still not loaded. Please wait..
        /// </summary>
        public static string XPG_Still_Loading {
            get {
                return ResourceManager.GetString("XPG_Still_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the data is.
        /// </summary>
        public static string XPG_Wait_Line1 {
            get {
                return ResourceManager.GetString("XPG_Wait_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded from the analysis server.
        /// </summary>
        public static string XPG_Wait_Line2 {
            get {
                return ResourceManager.GetString("XPG_Wait_Line2", resourceCulture);
            }
        }
    }
}
