//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTech.FrameWork.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SparklineStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SparklineStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllTech.FrameWork.Resources.SparklineStrings", typeof(SparklineStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Ranges.
        /// </summary>
        public static string XSL_AdjustRanges {
            get {
                return ResourceManager.GetString("XSL_AdjustRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Chart.
        /// </summary>
        public static string XSL_AreaChart {
            get {
                return ResourceManager.GetString("XSL_AreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Types.
        /// </summary>
        public static string XSL_ChartTypes {
            get {
                return ResourceManager.GetString("XSL_ChartTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chart.
        /// </summary>
        public static string XSL_ColumnChart {
            get {
                return ResourceManager.GetString("XSL_ColumnChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubicFit.
        /// </summary>
        public static string XSL_CubicFit {
            get {
                return ResourceManager.GetString("XSL_CubicFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CumulativeAverage.
        /// </summary>
        public static string XSL_CumulativeAverage {
            get {
                return ResourceManager.GetString("XSL_CumulativeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExponentialAverage.
        /// </summary>
        public static string XSL_ExponentialAverage {
            get {
                return ResourceManager.GetString("XSL_ExponentialAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExponentialFit.
        /// </summary>
        public static string XSL_ExponentialFit {
            get {
                return ResourceManager.GetString("XSL_ExponentialFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First / Last Markers.
        /// </summary>
        public static string XSL_First_Last_Markers {
            get {
                return ResourceManager.GetString("XSL_First_Last_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High / Low Markers.
        /// </summary>
        public static string XSL_High_Low_Markers {
            get {
                return ResourceManager.GetString("XSL_High_Low_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinearFit.
        /// </summary>
        public static string XSL_LinearFit {
            get {
                return ResourceManager.GetString("XSL_LinearFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Chart.
        /// </summary>
        public static string XSL_LineChart {
            get {
                return ResourceManager.GetString("XSL_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogarithmicFit.
        /// </summary>
        public static string XSL_LogarithmicFit {
            get {
                return ResourceManager.GetString("XSL_LogarithmicFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers.
        /// </summary>
        public static string XSL_Markers {
            get {
                return ResourceManager.GetString("XSL_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedAverage.
        /// </summary>
        public static string XSL_ModifiedAverage {
            get {
                return ResourceManager.GetString("XSL_ModifiedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Markers.
        /// </summary>
        public static string XSL_Negative_Markers {
            get {
                return ResourceManager.GetString("XSL_Negative_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string XSL_None {
            get {
                return ResourceManager.GetString("XSL_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerLawFit.
        /// </summary>
        public static string XSL_PowerLawFit {
            get {
                return ResourceManager.GetString("XSL_PowerLawFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuadraticFit.
        /// </summary>
        public static string XSL_QuadraticFit {
            get {
                return ResourceManager.GetString("XSL_QuadraticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuarticFit.
        /// </summary>
        public static string XSL_QuarticFit {
            get {
                return ResourceManager.GetString("XSL_QuarticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuinticFit.
        /// </summary>
        public static string XSL_QuinticFit {
            get {
                return ResourceManager.GetString("XSL_QuinticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleAverage.
        /// </summary>
        public static string XSL_SimpleAverage {
            get {
                return ResourceManager.GetString("XSL_SimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trendline Types.
        /// </summary>
        public static string XSL_TrendlineTypes {
            get {
                return ResourceManager.GetString("XSL_TrendlineTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightedAverage.
        /// </summary>
        public static string XSL_WeightedAverage {
            get {
                return ResourceManager.GetString("XSL_WeightedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinLoss Chart.
        /// </summary>
        public static string XSL_WinLossChart {
            get {
                return ResourceManager.GetString("XSL_WinLossChart", resourceCulture);
            }
        }
    }
}
